### ISSUE TITLE
module go version

### ISSUE THREAD

**Issue by ldez** [Antonboom/errname#26]
It's possible for you to downgrade the version inside your go.mod to go1.20?

the new way to handle the module and go version is strict.

https://github.com/golangci/golangci-lint/actions/runs/5893637045/job/15985603630?pr=4023

https://go.dev/blog/toolchain

https://github.com/golangci/golangci-lint/pull/4021

**Comment by Antonboom** [comment]
@ldez Hi! Done.

It's my bad – these linters are simple and do not require 1.21 API.
But what about the new ones?
