### ISSUE TITLE
Wrong report message for error array

### ISSUE THREAD

**Issue by ozon2** [Antonboom/errname#3]
The type `type MultiError []error` generates the following report: 
```the type name `MultiError` should conform to the `XxxError` format```

I think it should be ```the type name `MultiError` should conform to the `XxxErrors` format```.

**Comment by Antonboom** [comment]
@ozon2, thank u!

Yes it really looks better. Done.

But in your case it seems that `MultiError` is exception and it's better name than `MultiErrors`.
I would suggest using `//nolint:errname`.
