### ISSUE TITLE
Add case variable declaration with an error

### ISSUE THREAD

**Issue by micronull** [Antonboom/errname#31]
Bad:

```go
var someError error
var someFoo error
var failSome error
var er error
```

Good:

```go
var errSome error
var err error
```

**Comment by Antonboom** [comment]
@micronull, hi!

Thanks for the proposal.
But what specification confirms this rule?

**Comment by micronull** [comment]
@Antonboom 

>   Error types end in "Error" and error variables start with "Err" or "err".

https://go.dev/wiki/Errors#naming

It won't fit?

**Comment by Antonboom** [comment]
Initially this is about **error types** and **sentinel errors** only, but not about any variable.
But I'll think about it. Maybe you have examples from the standard library?

**Comment by micronull** [comment]
@Antonboom 

https://github.com/golang/sync/blob/59c1ca1e4661ed4452be4069ceea3c233f4deec1/errgroup/errgroup_test.go#L121

Yeah, you're right. 
This is not applicable for local variables.

I'm closing the proposal, but it could be a separate parameter.
