### ISSUE TITLE
Array and slice naming assumption

### ISSUE THREAD

**Issue by maraino** [Antonboom/errname#42]
Why is there an assumption of using the `XxxErrors` format for an array or slice? In many cases, it makes more sense to name them `XxxError`, for example:

```go
package flagutil

type IncompatiblePairError [2]string

func (e IncompatiblePairError) Error() string {
	return fmt.Sprintf("flag --%s is incompatible with --%s", e[0], e[1])
}
```

This will fail with:
```
.../flagutil/flagutil.go: the type name `IncompatiblePairError` should conform to the `XxxErrors` format
``` 

It clearly does not represent multiple errors. Since many examples can be created with a slice or an array, why not allow both?

**Comment by Antonboom** [comment]
Hello, @maraino 

It was introduced in https://github.com/Antonboom/errname/issues/3

But I found that both options are widely used

1. https://github.com/search?q=%2Ftype.*Errors+%5C%5B%2F+language%3AGo+&type=code
2. https://github.com/search?q=%2Ftype.*Error+%5C%5B%2F+language%3AGo+&type=code

So looks reasonable to reconsider this decision 👍

**Comment by Antonboom** [comment]
After fix:
```
$ errname util.go
/tmp/sandbox/util.go:5:6: the error type name `IncompatiblePairEror` should conform to the `XxxErrors` or `XxxError` format
```
