### ISSUE TITLE
[]byte type complains should conform to the `xxxError`

### ISSUE THREAD

**Issue by arvenil** [Antonboom/errname#5]
Should []byte slice defined as `type xxxError []byte` fail the check? Is `xxxErrors` pattern common in standard library?

**Comment by Antonboom** [comment]
@arvenil, hello!

It's the same of https://github.com/Antonboom/errname/issues/3

I already fixed it, but golangci-lint contains old version of linter.
Can u please do
```
go get -u github.com/Antonboom/errname
```

and check
```
errname ./...
```
?

**Comment by Antonboom** [comment]
Fixed in https://github.com/golangci/golangci-lint/releases/tag/v1.42.1

Be free to reopen issue if there is some problems.
